// <auto-generated />
namespace FOODSTATION.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class alterParticiTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alterParticiTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202307230748381_alterParticiTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
